package com.upnvjatim.silaturahmi.model.response

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class ItemPendaftarProgram(
    val akhirKegiatan: String?,
    val akhirPendaftaran: String?,
    val awalKegiatan: String?,
    val awalPendaftaran: String?,
    val createdAt: String?,
    val createdBy: String?,
    val id: String?,
    val idJenisMbkm: String?,
    val idJenisMitra: String?,
    val idMitra: String?,
    val idMitraTerlibatProgram: String?,
    val idPegawai: String?,
    val idPeriode: String?,
    val idPosisiKegiatanTopik: String?,
    val idProgram: String?,
    val idProgramDitawarkan: String?,
    val idProgramProdi: String?,
    val idSiamikMahasiswa: String?,
    val isDeleted: Boolean?,
    val isFinish: Boolean?,
    val isMagangMandiri: Boolean?,
    val kdJenisMbkm: String?,
    val kdPeriode: String?,
    val ketPenilaian: String?,
    val kuotaPerMitra: String?,
    val link: String?,
    val linkPenilaian: String?,
    val maxKrs: Int?,
    val maxSks: Int?,
    val nama: String?,
    val namaJenisMbkm: String?,
    val namaJenisMitra: String?,
    val namaMitra: String?,
    val namaPegawai: String?,
    val namaPosisiKegiatanTopik: String?,
    val namaProdi: String?,
    val namaProgram: String?,
    val nilaiAngka: String?,
    val nip: String?,
    val npm: String?,
    val semester: String?,
    val status: Int?,
    val statusApproval: String?,
    val statusMbkm: String?,
    val tahun: String?,
    val tglPenilaian: String?,
    val updatedAt: String?,
    val updatedBy: String?
) : Parcelable